### ISSUE TITLE
pip install py-zerox installation resulting in missing importable zerox module in python site-packages

### ISSUE THREAD

**Issue by pradhyumna85** [getomni-ai/zerox#30]
@tylermaran, fix for this is again a part of PR https://github.com/getomni-ai/zerox/pull/21, [commit](https://github.com/getomni-ai/zerox/pull/21/commits/b1c49322091b951e4182047da5b307b2148b23eb)

After a pip install:
```console
Downloading py_zerox-0.0.2-py3-none-any.whl (4.3 kB)
Installing collected packages: py-zerox
Successfully installed py-zerox-0.0.2
(zerox) pradhyumna85@machine:/mnt/c/Users/me$ python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import py_zerox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'py_zerox'
>>> import zerox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'zerox'
>>> from py_zerox import zerox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'py_zerox'
```

Missing module folder can also be confirmed from "pip uninstall" output (no module folder apart from scripts and dist info folder):
```console
(zerox) pradhyumna85@machine:/mnt/c/Users/me$ pip uninstall py-zerox
Found existing installation: py_zerox 0.0.2
Uninstalling py_zerox-0.0.2:
  Would remove:
    /home/pradhyumna85/miniforge3/envs/zerox/bin/py-zerox-pre-install
    /home/pradhyumna85/miniforge3/envs/zerox/lib/python3.11/site-packages/py_zerox-0.0.2.dist-info/*
Proceed (Y/n)? y
  Successfully uninstalled py_zerox-0.0.2
```

**Comment by pradhyumna85** [comment]
After a pip install:
```console
Downloading py_zerox-0.0.2-py3-none-any.whl (4.3 kB)
Installing collected packages: py-zerox
Successfully installed py-zerox-0.0.2
(zerox) pradhyumna85@MWKS645268:/mnt/c/Users/H250430$ python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import py_zerox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'py_zerox'
>>> import zerox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'zerox'
>>> from py_zerox import zerox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'py_zerox'
```
